Traceback (most recent call last):
  File "/home/sgeisser/git/plr-exercise/scripts/train.py", line 140, in <module>
    main()
  File "/home/sgeisser/git/plr-exercise/scripts/train.py", line 131, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "/home/sgeisser/git/plr-exercise/scripts/train.py", line 30, in train
    code_artifact.add_file('scripts/models/cnn.py')
  File "/home/sgeisser/.local/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 1157, in add_file
    raise ValueError("Path is not a file: %s" % local_path)
ValueError: Path is not a file: scripts/models/cnn.py
Traceback (most recent call last):
  File "/home/sgeisser/git/plr-exercise/scripts/train.py", line 140, in <module>
    main()
  File "/home/sgeisser/git/plr-exercise/scripts/train.py", line 131, in main
    train(args, model, device, train_loader, optimizer, epoch)
  File "/home/sgeisser/git/plr-exercise/scripts/train.py", line 30, in train
    code_artifact.add_file('scripts/models/cnn.py')
  File "/home/sgeisser/.local/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 1157, in add_file
    raise ValueError("Path is not a file: %s" % local_path)
ValueError: Path is not a file: scripts/models/cnn.py